name: Verificar Enlaces Rotos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar Linkinator
        run: npm install -g linkinator

      - name: Verificar enlaces rotos
        run: linkinator index.html --fail-on-error